#include <GL/glut.h>
#include <GL/gl.h>
#include <GL/glu.h>
#include <vector>
#include <cmath>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <iostream>
#include <stdio.h>
#include "tinyxml.h"
#include "tinystr.h"
#include <ctype.h>
#include <typeinfo>
#include <sstream>
#include <fstream>
#include <stdlib.h>
#include <vector>
#include <time.h>